### ISSUE TITLE
[Bug]: Button size inconsistency

### ISSUE THREAD

**Issue by emmalearnscode** [schmelto/LinkFree_generator#13]
### What happened?

<img width="178" alt="Screenshot 2022-06-11 190047" src="https://user-images.githubusercontent.com/57045550/173197692-f83e4e4e-41ca-4615-9e36-dec4ecbcc942.png">

The delete button should be the same height as the input fields and should be right aligned to match the alignment of the 'Add row' button

### What browsers are you seeing the problem on?

Chrome

**Comment by CodeAjay** [comment]
Hey, 

I want to work on this.
