### ISSUE TITLE
[Bug]: Responsivity

### ISSUE THREAD

**Issue by EmmaDawsonDev** [schmelto/LinkFree_generator#14]
### What happened?

<img width="284" alt="Screenshot 2022-06-11 191046" src="https://user-images.githubusercontent.com/57045550/173197788-5d85c9f8-03c8-4737-932a-cef36e8b1742.png">

Currently some fields overflow on ipad and mobile. Add mobile responsivity so that this works at all screen sizes.

### What browsers are you seeing the problem on?

Chrome

**Comment by schmelto** [comment]
This GitHub project will be archived soon, resulting in the closure of all open issues. Archiving means the repository becomes read-only, with no further updates or contributions accepted. Existing code and documentation will remain accessible for reference. Thank you for your support and understanding.
