### ISSUE TITLE
[Bug]: Need More Colums for Milestones

### ISSUE THREAD

**Issue by darkterminal** [schmelto/LinkFree_generator#27]
### What happened?

Missing Column for **color**
The Complete Milestones columns is:
- Title :heavy_check_mark: 
- Date :heavy_check_mark: 
- Icon :heavy_check_mark: 
- Color :heavy_multiplication_x: 
- Description :heavy_check_mark: 
- URL :heavy_check_mark: 

## Screenshot
![image](https://user-images.githubusercontent.com/32319439/173346813-9add4290-b7dd-4359-a99a-84a2fb386656.png)

**Comment by darkterminal** [comment]
@schmelto i think I will add Milestones using group of fields on card instead using table.

**Comment by schmelto** [comment]
This GitHub project will be archived soon, resulting in the closure of all open issues. Archiving means the repository becomes read-only, with no further updates or contributions accepted. Existing code and documentation will remain accessible for reference. Thank you for your support and understanding.
