### ISSUE TITLE
[Feat]: Add Spotify to list of icons

### ISSUE THREAD

**Issue by loftwah** [schmelto/LinkFree_generator#32]
### Feature request

I've added Spotify to the list of icons that are available for the profile.

**Comment by schmelto** [comment]
@loftwah I saw that you have committed changes to your fork (https://github.com/schmelto/LinkFree_generator/commit/f8a4d0839fd7c5cbb81d08959e4049e2047046b2) do you want to open a PR for the change?

**Comment by schmelto** [comment]
> If it is something, you'd want in the repo that would be cool. I didn't want to raise it without raising an issue first.

Sure

**Comment by loftwah** [comment]
We can close this issue as my dynamic icons supersede it.

**Comment by schmelto** [comment]
will be closed with #35 (issue #33)
