### ISSUE TITLE
[Feat]: add support for testimonials

### ISSUE THREAD

**Issue by loftwah** [schmelto/LinkFree_generator#44]
### Feature request

Our LinkFree profile generator should include a feature to support testimonials. Users should be able to enter their profile information, including their LinkFree username, and display the names of individuals who gave them testimonials. Additionally, the feature should provide a mechanism for users to enable or disable these testimonials using checkboxes or a similar approach.

**Comment by schmelto** [comment]
This GitHub project will be archived soon, resulting in the closure of all open issues. Archiving means the repository becomes read-only, with no further updates or contributions accepted. Existing code and documentation will remain accessible for reference. Thank you for your support and understanding.
